export type GenreSubStr_Type = 'Action' | 'Stealth' | 'Shooter' | 'Adventure' | 'FPS' | 'RTS';
export type GameMode_Type = 'Multiplayer' | 'Cooperative' | 'Single-player';

export interface GameCard_Type {
  release:     string,
  year:        number,
  fullName:    string,
  shortName:   string,
  genres:      GenreSubStr_Type[],
  mode:        GameMode_Type[],
  price:       number,
  platforms:   string[],
  developers:  string[],
  publishers:  string[],
  description: string
  cover?:      string
  id:          string,
  rating:      number,
}

//@ts-ignore
import { v4 as uuidv4 } from 'uuid'; //@ts-ignore


import Assassins_Creed_pic   from "@/dal/images/covers/Assassin's_Creed.jpg"; //@ts-ignore
import Assassins_Creed2_pic  from "@/dal/images/covers/Assassins_Creed_2.jpg"; //@ts-ignore
import Assassins_Creed3_pic  from "@/dal/images/covers/Assassin's_Creed_II_Discovery.jpg"; //@ts-ignore
import Assassins_Creed4_pic  from "@/dal/images/covers/Assassin's_Creed_3.jpg"; //@ts-ignore
import Assassins_Creed5_pic  from "@/dal/images/covers/Assassins_Creed_Brotherhood.jpg"; //@ts-ignore
import Assassins_Creed6_pic  from "@/dal/images/covers/Assassin's_Creed_III_Liberation.jpg"; //@ts-ignore
import Assassins_Creed7_pic  from "@/dal/images/covers/Assassin's_Creed_The Tyrany.png"; //@ts-ignore
import Assassins_Creed8_pic  from "@/dal/images/covers/Assassin's_Creed_IV_-_Black_Flag.jpg"; //@ts-ignore
import Assassins_Creed9_pic  from "@/dal/images/covers/Assassin's_Creed_4_Freedoms Cry.jpeg"; //@ts-ignore
import Assassins_Creed10_pic from "@/dal/images/covers/Assassin's_Creed_Syndicate_cover.jpg"; //@ts-ignore
import Assassins_Creed11_pic from "@/dal/images/covers/Assassin’s_Creed_Odyssey.jpg"; //@ts-ignore
import Assassins_Creed12_pic from "@/dal/images/covers/Assassin's_Creed_Valhalla_cover.jpg"; //@ts-ignore
import SplinterCell_pic  from "@/dal/images/covers/Splinter Cell.jpg"; //@ts-ignore
import SplinterCell2_pic from "@/dal/images/covers/Splinter_Cell_Pandora_Tomorrow.jpg";  //@ts-ignore
import SplinterCell3_pic from "@/dal/images/covers/Tom_Clancy's_Splinter_Cell_-_Chaos_Theory_Coverart.png"; //@ts-ignore
import SplinterCell4_pic from "@/dal/images/covers/Splinter_Cell_Double_Agent.jpg"; //@ts-ignore
import SplinterCell5_pic from "@/dal/images/covers/Tom_Clancy's_Splinter_Cell_Conviction.jpg"; //@ts-ignore
import SplinterCell6_pic from "@/dal/images/covers/Splinter_Cell_Blacklist_PC.jpg"; //@ts-ignore
import CoD     from "@/dal/images/covers/Call_of_Duty.jpg"; //@ts-ignore
import CoD2    from "@/dal/images/covers/Call_of_Duty_2_Box.jpg"; //@ts-ignore
import CoD3    from "@/dal/images/covers/Call_of_Duty_WWII_Cover_Art.jpg"; //@ts-ignore
import CoD4    from "@/dal/images/covers/call-of-duty-vanguard.jpg"; //@ts-ignore
import CoD5    from "@/dal/images/covers/Call_of_Duty_Modern_Warfare.jpg"; //@ts-ignore
import CoD6    from "@/dal/images/covers/CODMW_Remastered.jpg"; //@ts-ignore
import CoD7    from "@/dal/images/covers/Call_of_Duty_Modern_Warfare_2.png"; //@ts-ignore
import CoD8    from "@/dal/images/covers/Call_of_Duty_Modern_Warfare_3.png"; //@ts-ignore
import CoD9    from "@/dal/images/covers/CodMW.jpg"; //@ts-ignore
import CoD10   from "@/dal/images/covers/Call_of_Duty_Modern_Warfare_II.jpg"; //@ts-ignore
import Anno1   from "@/dal/images/covers/Anno_1602.png"; //@ts-ignore
import Anno2   from "@/dal/images/covers/Anno_1503.jpg"; //@ts-ignore
import Anno3   from "@/dal/images/covers/Anno_1701.jpg"; //@ts-ignore
import Anno4   from "@/dal/images/covers/Anno_1404.jpg"; //@ts-ignore
import Anno5   from "@/dal/images/covers/Anno_2070.jpg"; //@ts-ignore
import Anno6   from "@/dal/images/covers/Anno_2205.jpg"; //@ts-ignore
import Anno7   from "@/dal/images/covers/Anno_1800.png"; //@ts-ignore
import FarCry1 from "@/dal/images/covers/Far_Cry_1.jpg"; //@ts-ignore
import FarCry2 from "@/dal/images/covers/Far_Cry_2.jpg"; //@ts-ignore
import FarCry3 from "@/dal/images/covers/Far_Cry_3.jpg"; //@ts-ignore
import FarCry4 from "@/dal/images/covers/Far_Cry_4.jpg"; //@ts-ignore
import FarCry5 from "@/dal/images/covers/Far_Cry_5.jpg"; //@ts-ignore
import FarCry6 from "@/dal/images/covers/Far_cry_6.jpg"; //@ts-ignore
import Mafia1  from "@/dal/images/covers/Mafia1.jpg"; //@ts-ignore
import Mafia2  from "@/dal/images/covers/Mafia2.jpg"; //@ts-ignore
import Mafia3  from "@/dal/images/covers/Mafia3.jpg"; //@ts-ignore
import Mafia4  from "@/dal/images/covers/Mafia4.jpg"; //@ts-ignore
import Gta1    from "@/dal/images/covers/GTA1.jpg"; //@ts-ignore
import Gta2    from "@/dal/images/covers/GTA2.jpg"; //@ts-ignore
import Gta3    from "@/dal/images/covers/GTA3.jpg"; //@ts-ignore
import Gta4    from "@/dal/images/covers/GTA4.jpg"; //@ts-ignore
import Gta5    from "@/dal/images/covers/GTA5.png"; //@ts-ignore
import Rdr     from "@/dal/images/covers/RDR.jpg";  //@ts-ignore
import Rdr2    from "@/dal/images/covers/RDR2.jpg"; //@ts-ignore


export default [
    //RDR
  {
    id: '21615b76-0f22-4f6b-b3a6-ea84f928814b',
    release: 'November 5, 2019',
    year: 2019,
    rating: 10,
    cover: Rdr2,
    fullName:  'Red Dead Redemption 2',
    shortName: 'Red Dead Redemption 2',
    genres: ['Action', 'Adventure', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 150,
    platforms: ['Microsoft Windows','PlayStation 4', 'Xbox 360'],
    developers: ['Rockstar Studios'],
    publishers: ['Rockstar Games',],
    description: "Set in a fictional recreation of the American Old West in 1899, Red Dead Redemption 2 focuses on the life of Arthur Morgan and his position in the notorious Van der Linde gang. The game follows the gang's decline as they are pursued by lawmen, fellow gangs and Pinkerton agents.",
  },
  {
    id: '47d85e0f-055c-43e5-8cb4-aa959c96615c',
    release: 'May 18, 2010',
    year: 2010,
    rating: 9,
    cover: Rdr,
    fullName:  'Red Dead Redemption',
    shortName: 'Red Dead Redemption',
    genres: ['Action', 'Adventure', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 80,
    platforms: ['PlayStation 3', 'Xbox 360'],
    developers: ['Rockstar San Diego'],
    publishers: ['Rockstar Games',],
    description: "Red Dead Redemption is a Western-themed action-adventure game played from a third-person perspective. The player controls John Marston and completes missions—linear scenarios with set objectives—to progress through the story; in the game's epilogue, the player controls John's son Jack.",
  },
    // Gta
  {
    id: '65dabbd6-b1ea-4a90-98b4-10d85fd4c16c',
    release: 'September 17 2013',
    year: 2013,
    rating: 9.5,
    cover: Gta5,
    fullName:  'GTA V',
    shortName: 'Grand Theft Auto V',
    genres: ['Action', 'Adventure', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 90,
    platforms: ['Microsoft Windows', 'PlayStation 3', 'PlayStation 4', 'Xbox One', 'Xbox 360'],
    developers: ['Rockstar North'],
    publishers: ['Rockstar Games',],
    description: "Grand Theft Auto V is a 2013 action-adventure game developed by Rockstar North and published by Rockstar Games. Set within the fictional state of San Andreas, based on Southern California, the single-player story follows three protagonists—retired bank robber Michael De Santa, street gangster Franklin Clinton, and drug dealer and gunrunner Trevor Philips—and their attempts to commit heists while under pressure from a corrupt government agency and powerful criminals.",
  },
  {
    id: 'ccc79a59-a788-4414-b227-955fd5a051f8',
    release: '29 April 2008',
    year: 2008,
    rating: 9,
    cover: Gta4,
    fullName:  'GTA IV',
    shortName: 'Grand Theft Auto IV',
    genres: ['Action', 'Adventure', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 80,
    platforms: ['Microsoft Windows', 'PlayStation 3', 'Xbox 360'],
    developers: ['Rockstar North'],
    publishers: ['Rockstar Games',],
    description: "The game is played from a third-person perspective and its world is navigated on foot or by vehicle. Throughout the single-player mode, players control Niko Bellic. An online multiplayer mode is also included with the game, allowing up to 32 players to engage in both cooperative and competitive gameplay in a recreation of the single-player setting",
  },
  {
    id: '08e4de8c-5ffd-42a9-95f2-629b623ad245',
    release: 'October 23, 2001',
    year: 2001,
    rating: 7,
    cover: Gta3,
    fullName:  'GTA III',
    shortName: 'Grand Theft Auto III',
    genres: ['Action', 'Adventure', 'Shooter'],
    mode: ['Single-player'],
    price: 25,
    platforms: ['Microsoft Windows', 'PlayStation 2', 'Xbox'],
    developers: ['DMA Design'],
    publishers: ['Rockstar Games',],
    description: "Grand Theft Auto III is a 2001 action-adventure game developed by DMA Design and published by Rockstar Games. It is the third main entry in the Grand Theft Auto series, following 1999's Grand Theft Auto 2, and the fifth instalment overall. The game is played from a third-person perspective and its world is navigated on foot or by vehicle. Its open world design lets players freely roam Liberty City, consisting of three main areas."
  },
  {
    id: '71ef70d2-15e1-4418-a18e-8a7d07455a79',
    release: 'October 22 1999',
    year: 1999,
    rating: 6,
    cover: Gta2,
    fullName:  'GTA 2',
    shortName: 'Grand Theft Auto 2',
    genres: ['Action', 'Adventure', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 20,
    platforms: ['Microsoft Windows'],
    developers: ['DMA Design', 'Tarantula Studios (GBC)'],
    publishers: ['Rockstar Games',],
    description: "Game set within a retrofuturistic metropolis known as \"Anywhere City\", the game focuses on players taking the role of a criminal as they roam an open world, conducting jobs for various crime syndicates and having free rein to do whatever they wish to achieve their goal. The game's intro is unique for a title in the series, as it involved live-action scenes filmed by Rockstar Games.",
  },
  {
    id: 'df1a7825-d57e-4a98-9735-7817ca9cbf65',
    release: 'November 28, 1997',
    year: 1997,
    rating: 6,
    cover: Gta1,
    fullName:  'GTA 1',
    shortName: 'Grand Theft Auto 1',
    genres: ['Action', 'Adventure', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 20,
    platforms: ['Microsoft Windows'],
    developers: ['DMA Design', 'Tarantula Studios (GBC)'],
    publishers: ['BMG Interactive', 'ASC Games',],
    description: "Grand Theft Auto is an action-adventure video game developed by DMA Design and published by BMG Interactive.  The gameplay is presented from a top-down perspective and takes place within an open-world environment in which the player is not required to perform missions, although they are necessary to progress through the levels.",
  },
    // Mafia
  {
    id: 'ebd40a75-923f-4264-b5ed-fdbe78db82f7',
    release: 'September 25, 2020',
    year: 2020,
    rating: 7,
    cover: Mafia4,
    fullName:  'Mafia: Definitive Edition',
    shortName: 'Mafia: Definitive Edition',
    genres: ['Action'],
    mode: ['Single-player'],
    price: 160,
    platforms: ['Microsoft Windows', "PlayStation 4",  "Xbox One",],
    developers: ['Hangar 13'],
    publishers: ['2K'],
    description: "Mafia: Definitive Edition is a 2020 action-adventure game developed by Hangar 13 and published by 2K. It is a remake of the 2002 video game Mafia. Like the original game, the remake is set within the fictional city of Lost Heaven, Illinois, during the 1930s, and follows the rise and fall of Tommy Angelo, a Sicilian American cab driver-turned-gangster, within the Salieri crime family",
  },
  {
    id: '1da0b92d-8b0e-46db-9f44-33b480046d84',
    release: 'October 7, 2016',
    year: 2016,
    rating: 5,
    cover: Mafia3,
    fullName:  'Mafia III',
    shortName: 'Mafia III',
    genres: ['Action'],
    mode: ['Single-player'],
    price: 140,
    platforms: ['Microsoft Windows', "PlayStation 4",  "Xbox One",],
    developers: ['Hangar 13'],
    publishers: ['2K Games'],
    description: "Mafia III is an action-adventure game set in an open world environment and played from a third-person perspective, in which the player assume control of Lincoln Clay, a Vietnam War veteran on a quest to seek revenge for his adopted family, who are murdered by local mobs",
  },
  {
    id: '21f3371e-c15b-4b82-a825-1682fe611e3c',
    release: 'August 24, 2010',
    year: 2010,
    rating: 8,
    cover: Mafia2,
    fullName:  'Mafia II',
    shortName: 'Mafia II',
    genres: ['Action'],
    mode: ['Single-player'],
    price: 150,
    platforms: ['Microsoft Windows',  "PlayStation 3", "PlayStation 4",  "Xbox 360", "Xbox One",],
    developers: ['2K Czech'],
    publishers: ['2K Games'],
    description: "Mafia II is an action-adventure game set in an open world environment and played from a third-person perspective. Most of the game is set in the fictional city of Empire Bay, based on New York City, Chicago, San Francisco, Los Angeles, Boston, and Detroit, during the mid-1940s and early 1950s",
  },
  {
    id: '7eab7eaf-b74b-4118-84b0-7ce674eadfc4',
    release: 'August 29, 2002',
    year: 2002,
    rating: 10,
    cover: Mafia1,
    fullName:  'Mafia: The city of Lost Heaven',
    shortName: 'Mafia',
    genres: ['Action'],
    mode: ['Single-player'],
    price: 200,
    platforms: ['Microsoft Windows',  "PlayStation 2",  "Xbox"],
    developers: ['Illusion Softworks'],
    publishers: ['Gathering of Developers'],
    description: "It is the first installment in the Mafia series. Set within the fictional city of Lost Heaven, Illinois, during the 1930s, the story follows the rise and fall of taxi driver-turned-mobster Tommy Angelo within the Salieri crime family",
  },
    // Far Cry
  {
    id: '8db512de-6769-4af6-8cb7-25c6f71f0fee',
    release: 'October 7, 2021',
    year: 2021,
    rating: 9,
    cover: FarCry6,
    fullName:  'Far Cry 6',
    shortName: 'Far Cry 6',
    genres: ['FPS', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 200,
    platforms: ['Microsoft Windows',  "PlayStation 4", "PlayStation 5", "Xbox One"],
    developers: ['Ubisoft Toronto'],
    publishers: ['Ubisoft'],
    description: "Far Cry 6 thrusts players into the adrenaline-filled world of a modern-day guerrilla revolution. As dictator of Yara, Antón Castillo is intent on restoring his nation back to its former glory by any means, with his son, Diego, dutifully at his side. Become a guerrilla fighter and burn their regime to the ground",
  },
  {
    id: 'd50b5a4c-ab48-4b98-bd56-80a3e7d66df0',
    release: 'November 3, 2020',
    year: 2020,
    rating: 9,
    cover: FarCry5,
    fullName: 'Far Cry 5',
    shortName: 'Far Cry 5',
    genres: ['FPS', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 170,
    platforms: ['Microsoft Windows',  "PlayStation 4", "Xbox One"],
    developers: ['Ubisoft Montreal', 'Ubisoft Toronto'],
    publishers: ['Ubisoft'],
    description: "Set in Hope County, a fictional region of Montana, United States, the game revolves around the Project at Eden's Gate, a doomsday cult that has taken over the county at the command of its charismatic and powerful leader, Joseph Seed",
  },
  {
    id: '1ec9bfda-68ff-4bb5-98f6-5cae803d6caa',
    release: 'November 18, 2014',
    year: 2014,
    rating: 9,
    cover: FarCry4,
    fullName:  'Far Cry 4',
    shortName: 'Far Cry 4',
    genres: ['FPS', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 170,
    platforms: ['Microsoft Windows',  "PlayStation 4", "Xbox One"],
    developers: ['Ubisoft Montreal', 'Ubisoft Toronto'],
    publishers: ['Ubisoft'],
    description: "Far Cry 4 is a first-person action-adventure game. Players assume control of Ajay Ghale, a Kyrati-American who is on a quest to spread his deceased mother's ashes in the fictional country of Kyrat",
  },
  {
    id: 'a6366f38-4aa1-451b-8d82-031355f1329a',
    release: 'November 29, 2012',
    year: 2012,
    rating: 10,
    cover: FarCry3,
    fullName: 'Far Cry 3',
    shortName: 'Far Cry 3',
    genres: ['FPS', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 120,
    platforms: ['Microsoft Windows', "PlayStation 3", "Xbox 360", "PlayStation 4", "Xbox One"],
    developers: ['Ubisoft Montreal'],
    publishers: ['Ubisoft'],
    description: "Far Cry 3 is a first-person shooter set on the fictional Rook Islands, a tropical archipelago somewhere in the Pacific, controlled by pirates and mercenaries. Players control Jason Brody and can approach missions and objectives in a variety of ways",
  },
  {
    id: '28e6e625-aa96-4705-8e25-2ded24d02f2a',
    release: 'October 21, 2008',
    year: 2008,
    rating: 7,
    cover: FarCry2,
    fullName: 'Far Cry 2',
    shortName: 'Far Cry 2',
    genres: ['FPS', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 60,
    platforms: ['Microsoft Windows', "PlayStation 3", "Xbox 360"],
    developers: ['Ubisoft Montreal'],
    publishers: ['Ubisoft'],
    description: "Set in a fictional East African country engulfed in civil war, the storyline follows a mercenary who is assigned to kill the Jackal, a weapons dealer inflaming the conflict. The player navigates the open world, completing missions for factions and allies called Buddies while managing their health and equipment",
  },
  {
    id: '2e99b315-b56c-48b8-9b5e-a91eb3a8f9f4',
    release: 'March 23, 2004',
    year: 2004,
    rating: 8,
    cover: FarCry1,
    fullName: 'Far Cry',
    shortName: 'Far Cry',
    genres: ['FPS', 'Shooter'],
    mode: ['Multiplayer', 'Single-player'],
    price: 90,
    platforms: ['Microsoft Windows', "PlayStation 3", "Xbox 360"],
    developers: ['Crytek'],
    publishers: ['Ubisoft'],
    description: "Far Cry is a 2004 first-person shooter game developed by Crytek and published by Ubisoft. It is the first installment in the Far Cry franchise. Set on a mysterious tropical archipelago, the game follows Jack Carver, a former American special forces operative, as he searches for the female journalist, Valerie Constantine, who accompanied him to the islands but went missing after their boat was destroyed by mercenaries",
  },
    //Anno
  {
    id: '008e356c-1e9b-4a05-9cae-b14ef4323ca6',
    release: 'April 16, 2019',
    year: 2019,
    rating: 10,
    cover: Anno7,
    fullName: 'Anno 1800',
    shortName: 'Anno 1800',
    genres: ['RTS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 150,
    platforms: ['Microsoft Windows'],
    developers: ['Related Designs', 'Blue Byte'],
    publishers: ['Ubisoft'],
    description: "Anno 1800 is a city-building real-time strategy video game, developed by Blue Byte and published by Ubisoft, and launched on April 16, 2019.[1] It is the seventh game in the Anno series, and returns to the use of a historical setting following the last two titles, Anno 2070 and Anno 2205, taking place during the Industrial Revolution in the 19th century",
  },
  {
    id: 'd7e16277-df9f-4617-96b0-81b50b524133',
    release: 'November 3, 2015',
    year: 2015,
    rating: 7,
    cover: Anno6,
    fullName: 'Anno 2205',
    shortName: 'Anno 2205',
    genres: ['RTS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 80,
    platforms: ['Microsoft Windows'],
    developers: ['Related Designs', 'Blue Byte'],
    publishers: ['Ubisoft'],
    description: "Anno 2205 is a city-building and economic simulation game, with real-time strategy elements, developed by Blue Byte and published by Ubisoft. Anno 2205 is the sixth game of the Anno series, and was released worldwide on 3 November 2015. As with Anno 2070, the game is set in the future, with players having the opportunity to set up colonies on the Moon",
  },
  {
    id: '52933cd4-50ea-44e3-acb5-20d5400fe477',
    release: 'November 17, 2011',
    year: 2011,
    rating: 9,
    cover: Anno5,
    fullName: 'Anno 2070',
    shortName: 'Anno 2070',
    genres: ['RTS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 80,
    platforms: ['Microsoft Windows'],
    developers: ['Related Designs', 'Blue Byte'],
    publishers: ['Ubisoft'],
    description: "Anno 2070 is a city-building and economic simulation game, with real-time strategy elements. It is the 5th game of the Anno series. It was released on 17 November 2011, and was co-developed by the German studios Related Designs and Blue Byte, and published by Ubisoft. Anno 2070 required Uplay to operate as an always online DRM System, later removed for receiving severe criticism from players",
  },
  {
    id: 'c351dd9e-beb8-411e-9baf-2d94537b146b',
    release: 'June 25, 2009',
    year: 2009,
    rating: 8,
    cover: Anno4,
    fullName: 'Anno 1404',
    shortName: 'Anno 1404',
    genres: ['RTS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 80,
    platforms: ['Microsoft Windows'],
    developers: ['Related Designs', 'Blue Byte'],
    publishers: ['Ubisoft'],
    description: "Anno 1404, known as Dawn of Discovery in North America, is a city-building and economic simulation game with real-time strategy elements, part of the Anno series.",
  },
  {
    id: 'b480c119-813c-43ce-bdf7-2b8313edc27a',
    release: 'October 26, 2006',
    year: 2006,
    rating: 6,
    cover: Anno3,
    fullName: 'Anno 1701',
    shortName: 'Anno 1701',
    genres: ['RTS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 60,
    platforms: ['Microsoft Windows'],
    developers: ['Related Designs'],
    publishers: ['Sunflowers Interactive', 'Deep Silver', 'Ubisoft (History Edition)'],
    description: "Game revolves around building and maintaining an 18th-century colony in the \"New World\". With a budget of €10 million, it was the most expensive German game ever produced by 2006. It is the sequel to Anno 1602 and Anno 1503 and was followed by Anno 1404.",
  },
  {
    id: '9cfc72f0-dc07-4357-8fe7-675181df83d2',
    release: 'October 25, 2002',
    year: 2002,
    rating: 5,
    cover: Anno2,
    fullName: 'Anno 1503: The New World',
    shortName: 'Anno 1503',
    genres: ['RTS'],
    mode: ['Single-player'],
    price: 45,
    platforms: ['Microsoft Windows'],
    developers: ['Max Design'],
    publishers: ['Sunflowers Interactive', 'EA Games', 'Ubisoft (History Edition)'],
    description: "Anno 1503: The New World (released as 1503 A.D.: The New World in North America) is a 2002 construction and management simulation video game developed by Austrian developer Max Design and published by Sunflowers Interactive.",
  },
  {
    id: '7f7dc47d-6529-4b0d-b62b-d34b1a4552e5',
    release: 'September 24, 1998',
    year: 1998,
    rating: 5,
    cover: Anno1,
    fullName: 'Anno 1602: Creation of a New World',
    shortName: 'Anno 1602',
    genres: ['RTS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 40,
    platforms: ['Microsoft Windows'],
    developers: ['Max Design'],
    publishers: ['Sunflowers Interactive', 'GT Interactive', 'Ubisoft (History Edition)'],
    description: 'Set in the early modern period, it requires the player to build colonies on small islands and manage resources, exploration, diplomacy and trade. The game design is noteworthy for its attempt to implement a \'progressive\' artificial intelligence, meaning that the pace of the game changes in response to how quickly players act.',
  },
    //Assassin's Creed
  {
    id: '5239fbed-67ea-4f03-b289-9f7284ede1c4',
    release: 'November 13, 2007',
    year: 2007,
    rating: 6,
    cover: Assassins_Creed_pic,
    fullName: 'Assassin\'s Creed',
    shortName: 'Assassin\'s Creed',
    genres: ['Action', 'Stealth'],
    mode: ['Single-player'],
    price: 70,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch'],
    developers: ['Ubisoft Montréal'],
    publishers: ['Ubisoft'],
    description: 'Assassin\'s Creed is an action-adventure video game developed by Ubisoft Montreal and published by Ubisoft. It is the first installment in the Assassin\'s Creed series. The game was released for PlayStation 3 and Xbox 360 in November 2007. A Microsoft Windows version titled Assassin\'s Creed: Director\'s Cut Edition and containing additional content was released in April 2008.',
  },
  {
    id: '57bb3b1f-a90d-4fa3-90ca-cc4b0b00016f',
    release: 'November 17, 2009',
    year: 2009,
    rating: 3,
    cover: Assassins_Creed2_pic,
    fullName: 'Assassin\'s Creed II',
    shortName: 'Assassin\'s Creed II',
    genres: ['Action', 'Stealth'],
    mode: ['Single-player'],
    price: 75,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch'],
    developers: ['Ubisoft Montréal'],
    publishers: ['Ubisoft'],
    description: 'Assassin\'s Creed 2 tells the story of Desmond Miles, who is tossed into a historical conflict between Assassins and Templars. Desmond\'s story takes place in modern times, where he must use a machine called an Animus to relive the memories of his ancestor Ezio Auditore.',
  },
  {
    id: '1f726acd-fec9-44c9-9702-f68ada9f7a6e',
    release: 'November 17, 2009',
    year: 2010,
    rating: 3,
    cover: Assassins_Creed3_pic,
    fullName: 'Assassin\'s Creed II: Discovery',
    shortName: 'Assassin\'s Creed II: Discovery',
    genres: ['Action', 'Stealth'],
    mode: ['Single-player'],
    price: 75,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch'],
    developers: ['Griptonite Games'],
    publishers: ['Ubisoft'],
    description: 'The story takes place from 1491 to 1492, and follows Ezio Auditore da Firenze (the protagonist of Assassin\'s Creed II) as he travels to Spain to help his fellow Assassins, who are being hunted by the Templar Order under the guise of the Spanish Inquisition',
  },
  {
    id: '35953744-9f7f-4716-86a0-ae0b909dfaad',
    release: 'November 16, 2010',
    year: 2010,
    rating: 4,
    cover: Assassins_Creed5_pic,
    fullName: 'Assassin\'s Creed II: Brotherhood',
    shortName: 'Assassin\'s Creed II: Brotherhood',
    genres: ['Action', 'Stealth'],
    mode: ['Multiplayer', 'Single-player'],
    price: 75,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch'],
    developers: ['Ubisoft Montreal'],
    publishers: ['Ubisoft'],
    description: 'The main story takes place during the Italian Wars, spanning the years 1500–1507, and continues from the events of Assassin\'s Creed II, as Ezio takes the fight against the Templars (led by the powerful Borgia family) to Rome, where he attempts to rebuild the Assassin Brotherhood in Italy and liberate the city',
  },
  {
    id: 'e64ea048-fc52-4e6c-a640-af93a7e4c84f',
    release: 'October 30, 2012',
    year: 2012,
    rating: 5,
    cover: Assassins_Creed4_pic,
    fullName: 'Assassin\'s Creed III',
    shortName: 'Assassin\'s Creed III',
    genres: ['Action', 'Stealth'],
    mode: ['Multiplayer', 'Single-player'],
    price: 75,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch'],
    developers: ['Ubisoft Montréal'],
    publishers: ['Ubisoft'],
    description: 'The main story is set in the 18th century, before, during and after the American Revolution from 1760 to 1783, and follows Desmond\'s half-English, half-Mohawk ancestor, Ratonhnhaké:ton / Connor, as he fights the Templars\' attempts to gain control of the colonies.',
  },
  {
    id: 'a3d5b3d4-c083-4f69-af62-dd979e0dfab6',
    release: 'October 30, 2012',
    year: 2012,
    rating: 8,
    cover: Assassins_Creed6_pic,
    fullName: 'Assassin\'s Creed III: Liberation',
    shortName: 'Assassin\'s Creed III: Liberation',
    genres: ['Action', 'Stealth'],
    mode: ['Multiplayer', 'Single-player'],
    price: 70,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch'],
    developers: ['Ubisoft Sofia', 'Ubisoft Milan'],
    publishers: ['Ubisoft'],
    description: 'Assassin\'s Creed III: Liberation is a 2012 action-adventure video game developed by Ubisoft Sofia and published by Ubisoft. It was originally released for the PlayStation Vita on October 30, 2012, in North America, with a worldwide launch the following day. It is the fourth spin-off installment in the Assassin\'s Creed series, and takes place alongside the events of Assassin\'s Creed III.',
  },
  {
    id: 'e155b62b-9313-48d3-a8c0-a5e0defb6f08',
    release: 'April 2013',
    year: 2013,
    rating: 10,
    cover: Assassins_Creed7_pic,
    fullName:  'Assassin\'s Creed III: The Tyranny of King Washington',
    shortName: 'Assassin\'s Creed III: TTKW',
    genres: ['Action', 'Stealth'],
    mode: ['Single-player'],
    price: 80,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch', 'Wii U'],
    developers: ['Ubisoft Montreal'],
    publishers: ['Ubisoft'],
    description: 'It is a downloadable content (DLC) expansion pack developed and published by Ubisoft for the 2012 action-adventure video game Assassin\'s Creed III.',
  },
  {
    id: '67303368-1080-4bb0-b872-899c178a0e34',
    release: 'October 29, 2013',
    year: 2013,
    rating: 10,
    cover: Assassins_Creed8_pic,
    fullName:  'Assassin’s Creed IV: Black Flag',
    shortName: 'Assassin’s Creed IV: Black Flag',
    genres: ['Action', 'Stealth'],
    mode: ['Multiplayer', 'Single-player'],
    price: 90,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch', 'Wii U'],
    developers: ['Ubisoft Montreal'],
    publishers: ['Ubisoft'],
    description: 'Assassin\'s Creed IV: Black Flag is a 2013 action-adventure video game developed by Ubisoft Montreal and published by Ubisoft. It is the sixth major installment in the Assassin\'s Creed series. Its historical timeframe precedes that of Assassin\'s Creed III (2012), but its modern-day sequences succeed III\'s own. ',
  },
  {
    id: '73650bdb-49b3-4f92-8f42-ab80631eec66',
    release: 'December 17, 2013',
    year: 2013,
    rating: 5,
    cover: Assassins_Creed9_pic,
    fullName:  'Assassin\'s Creed Freedom Cry',
    shortName: 'Assassin\'s Creed Freedom Cry',
    genres: ['Action', 'Stealth'],
    mode: ['Single-player'],
    price: 90,
    platforms: ['Xbox 360', 'PlayStation 3', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch', 'Wii U'],
    developers: ['Ubisoft Montreal'],
    publishers: ['Ubisoft'],
    description: '15 years later, Adewale has become a trained Assassin who finds himself shipwrecked in Saint-Domingue without weapons or crew. He now has to acquire a ship and gather his own crew to free the slaves and avenge them. Over 3 hours of new single-player gameplay!',
  },
  {
    id: '347e2e6d-f033-4cd0-8dd9-92c59f369adc',
    release: 'October 23, 2015',
    year: 2015,
    rating: 6,
    cover: Assassins_Creed10_pic,
    fullName:  'Assassin\'s Creed Syndicate',
    shortName: 'Assassin\'s Creed Syndicate',
    genres: ['Action', 'Stealth'],
    mode: ['Single-player'],
    price: 110,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'PlayStation 5', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch', ],
    developers: ['Ubisoft Montreal'],
    publishers: ['Ubisoft'],
    description: 'Assassin\'s Creed Syndicate is an action-adventure video game developed by Ubisoft Quebec and published by Ubisoft. It was released on October 23, 2015, for PlayStation 4 and Xbox One, and on November 19, 2015, for Microsoft Windows. It is the ninth major installment in the Assassin\'s Creed series, and the successor to 2014\'s Assassin\'s Creed Unity.',
  },
  {
    id: '76a9b4c9-067f-43a7-8502-d49e548af75b',
    release: 'October 5, 2018',
    year: 2018,
    rating: 8,
    cover: Assassins_Creed11_pic,
    fullName:  'Assassin\'s Creed Odyssey',
    shortName: 'Assassin\'s Creed Odyssey',
    genres: ['Action', 'Stealth'],
    mode: ['Single-player'],
    price: 130,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'PlayStation 5', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch'],
    developers: ['Ubisoft Quebec'],
    publishers: ['Ubisoft'],
    description: 'The game\'s plot tells a mythological history of the Peloponnesian War between Athens and Sparta from 431 to 422 BC. Players control a Spartan mercenary, who fights on both sides of the conflict as they attempt to find their family and eliminate the mysterious Cult of Kosmos',
  },
  {
    id: '48e436af-ed2b-40cc-93af-3b7d3a0147b0',
    release: 'November 10, 2020',
    year: 2020,
    rating: 9,
    cover: Assassins_Creed12_pic,
    fullName:  'Assassin\'s Creed Valhalla',
    shortName: 'Assassin\'s Creed Valhalla',
    genres: ['Action', 'Stealth'],
    mode: ['Single-player'],
    price: 150,
    platforms: ['Xbox 360', 'PlayStation 3', 'PlayStation 4', 'PlayStation 5', 'Microsoft Windows', 'Xbox One', 'Nintendo Switch', ],
    developers: ['Ubisoft Montreal'],
    publishers: ['Ubisoft'],
    description: 'In Assassin\'s Creed Valhalla, become Eivor, a legendary Viking raider on a quest for glory. Explore a dynamic and beautiful open world set against the brutal backdrop of England\'s Dark Ages. Raid your enemies, grow your settlement, and build your political power in the quest to earn a place among the gods in Valhalla',
  },
    //splinter Sell
  {
    id: 'a74e835c-7490-46f8-a69f-52935b363385',
    release: 'November 17, 2002',
    year: 2013,
    rating: 7,
    cover: SplinterCell_pic,
    fullName:  'Tom Clancy\'s Splinter Cell',
    shortName: 'Splinter Cell',
    genres: ['Shooter', 'Stealth'],
    mode: ['Single-player'],
    price: 100,
    platforms: ['Xbox 360', 'PlayStation 2',  'PlayStation 3', 'Microsoft Windows', 'Xbox', 'Xbox 360'],
    developers: ['Ubisoft Montreal', 'Ubisoft Milan', 'Ubisoft Shanghai', 'Ubisoft Toronto', 'Gameloft', 'Red Storm Entertainment'],
    publishers: ['Ubisoft', 'Microsoft Game Studios', 'Gameloft', 'Aspyr Media'],
    description: 'Stealth-mission expert Sam Fisher searches for two US agents in Georgia and soon uncovers a plot involving a nuclear device. When two government operatives undercover in Georgia go missing, Sam is sent in by the Third Echelon to investigate',
  },
  {
    id: '131ebd54-5e64-4e6a-b96c-54f231baaa35',
    release: 'March 23, 2004',
    year: 2004,
    rating: 6,
    cover: SplinterCell2_pic,
    fullName:  'Tom Clancy\'s Splinter Cell: Pandora Tomorrow',
    shortName: 'Splinter Cell: Pandora Tomorrow',
    genres: ['Shooter', 'Stealth'],
    mode: ['Multiplayer', 'Single-player'],
    price: 110,
    platforms:  ['Xbox 360', 'PlayStation 2',  'PlayStation 3', 'Microsoft Windows', 'Xbox', ],
    developers: ['Ubisoft Milan', 'Ubisoft Shanghai'],
    publishers: ['Ubisoft'],
    description: 'Stealth-mission expert Sam Fisher is sent after a terrorist, who leads an operation involving setting up bombs with the smallpox virus on US territory.',
  },
  {
    id: 'e1b6b17e-7299-40f7-bcf5-eb731910c9a3',
    release: 'March 21, 2005',
    year: 2005,
    rating: 8,
    cover: SplinterCell3_pic,
    fullName:  'Tom Clancy\'s Splinter Cell: Chaos Theory',
    shortName: 'Splinter Cell: Chaos Theory',
    genres: ['Shooter', 'Stealth'],
    mode: ['Multiplayer', 'Single-player'],
    price: 135,
    platforms:  ['PlayStation 2',  'PlayStation 3', 'Microsoft Windows', 'Xbox', ],
    developers: ['Ubisoft Milan', 'Ubisoft Montreal'],
    publishers: ['Ubisoft'],
    description: 'Chaos Theory is the third game in the Splinter Cell series endorsed by novelist Tom Clancy. As with previous entries in the franchise, Chaos Theory follows the activities of Sam Fisher, an agent working for a covert-ops branch within the NSA called "Third Echelon"',
  },
  {
    id: '77728013-cfb9-41af-a2dc-8b933d6c8f4f',
    release: 'October 17, 2006',
    year: 2006,
    rating: 3,
    cover: SplinterCell4_pic,
    fullName:  'Tom Clancy\'s Splinter Cell: Double Agent',
    shortName: 'Splinter Cell: Double Agent',
    genres: ['Shooter', 'Stealth'],
    mode: ['Multiplayer', 'Single-player'],
    price: 115,
    platforms:  ['PlayStation 2',  'PlayStation 3', 'Microsoft Windows', 'Xbox', 'Xbox 360',],
    developers: ['Ubisoft Milan', 'Ubisoft Shanghai'],
    publishers: ['Ubisoft', 'Microsoft Game Studios'],
    description: "Splinter Cell Double Agent is a Stealth-Action game where you play as Sam Fisher, a secret NSA agent, infiltrating a terrorist cell to destroy it from within. Face the gut-wrenching dilemmas of a Double Agent's life, do whatever it takes to complete your mission, and get out alive",
  },
  {
    id: '91698b10-4bcd-4dd1-8ccd-fb3d6ce6862d',
    release: 'April 13, 2010',
    year: 2010,
    rating: 6,
    cover: SplinterCell5_pic,
    fullName:  'Tom Clancy\'s Splinter Cell: Conviction',
    shortName: 'Splinter Cell: Conviction',
    genres: ['Shooter', 'Stealth', 'Adventure'],
    mode: ['Cooperative', 'Single-player'],
    price: 115,
    platforms:  ['Microsoft Windows', 'Xbox 360',],
    developers: ['Ubisoft Montreal'],
    publishers: ['Ubisoft', 'Microsoft Game Studios'],
    description: "An investigation into his daughter's death unwittingly leads former agent Sam Fisher to discover he's been betrayed by his prior agency, the Third Echelon. Now a renegade, Fisher finds himself in a race against time to thwart a deadly terrorist plot that threatens millions",
  },
  {
    id: '1c78602d-55e2-4279-a3e2-50b5dfb8aac5',
    release: 'August 23, 2013',
    year: 2013,
    rating: 9,
    cover: SplinterCell6_pic,
    fullName:  'Tom Clancy\'s Splinter Cell: Blacklist',
    shortName: 'Splinter Cell: Blacklist',
    genres: ['Shooter', 'Stealth', 'Adventure'],
    price: 150,
    mode: ['Multiplayer', 'Cooperative', 'Single-player'],
    platforms:  ['Microsoft Windows', 'Xbox 360','PlayStation 3',],
    developers: ['Ubisoft Toronto'],
    publishers: ['Ubisoft'],
    description: "In Blacklist, players assume control of series protagonist Sam Fisher as he seeks to stop a terrorist group called the Engineers. The gameplay emphasizes stealth, and utilizes the third-person perspective. During the game, players can rotate its camera, run, crouch and leap over obstacles",
  },
  // Call of Duty
  {
    id: 'a2b09b0b-4974-47ac-ba71-254bf6e45bca',
    release: 'October 29, 2003',
    year: 2003,
    rating: 6,
    cover: CoD,
    fullName:  'Call of Duty',
    shortName: 'Call of Duty',
    genres: ['FPS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 150,
    platforms:  ['Microsoft Windows', 'Xbox 360','PlayStation 3',],
    developers: ['Infinity Ward'],
    publishers: ['Activision'],
    description: 'Call of Duty is a first-person shooter video game based on id Tech 3, and was released on October 29, 2003. The game was developed by Infinity Ward and published by Activision. The game simulates the infantry and combined arms warfare of World War II. An expansion pack, Call of Duty: United Offensive, was developed by Gray Matter Studios with contributions from Pi Studios and produced by Activision. The game follows American and British paratroopers and the Red Army.',
  },
  {
    id: '2cf00cd4-bb15-4505-903f-3c338db66791',
    release: 'November 22, 2005',
    year: 2005,
    rating: 4,
    cover: CoD2,
    fullName:  'Call of Duty 2',
    shortName: 'Call of Duty 2',
    genres: ['FPS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 99,
    platforms:  ['Microsoft Windows', 'Xbox 360',],
    developers: ['Infinity Ward'],
    publishers: ['Activision'],
    description: 'Call of Duty 2 is a 2005 first-person shooter video game developed by Infinity Ward and published by Activision in most regions of the world. It is the second installment of the Call of Duty series. Announced by Activision on April 7, 2005, the game was released for Microsoft Windows on October 25, 2005, and as a launch title for the Xbox 360 on November 22, 2005. Other versions were eventually released for OS X, mobile phones, and Pocket PCs.',
  },
  {
    id: '75a4642b-b75b-4443-9137-b88ff121b5e5',
    release: 'November 3, 2017',
    year: 2017,
    rating: 7,
    cover: CoD3,
    fullName:  'Call of Duty: WWII',
    shortName: 'Call of Duty: WWII',
    genres: ['FPS'],
    mode: ['Multiplayer', 'Cooperative', 'Single-player'],
    price: 125,
    platforms:  ['Microsoft Windows', 'PlayStation 4','Xbox One'],
    developers: ['Sledgehammer Games'],
    publishers: ['Activision'],
    description: 'Call of Duty: WWII is a 2017 first-person shooter game developed by Sledgehammer Games and published by Activision. It was released worldwide on November 3, 2017 for Microsoft Windows, PlayStation 4 and Xbox One. It is the fourteenth main installment in the Call of Duty series and the first title in the series to be set primarily during World War II since Call of Duty: World at War in 2008.',
  },
  {
    id: 'ba1182d9-417c-4aad-b66c-f4d335d2adf9',
    release: 'November 5, 2021',
    year: 2021,
    rating: 5,
    cover: CoD4,
    fullName:  'Call of Duty: Vanguard',
    shortName: 'Call of Duty: Vanguard',
    genres: ['FPS'],
    mode: ['Multiplayer', 'Cooperative', 'Single-player', /*'Battle Royale'*/],
    price: 170,
    platforms:  ['Microsoft Windows', 'PlayStation 4', 'PlayStation 5','Xbox One'],
    developers: ['Sledgehammer Games'],
    publishers: ['Activision'],
    description: "The award-winning Call of Duty® series returns with Call of Duty®: Vanguard, in which players will experience influential battles of World War II as they fight for victory across the Eastern and Western Fronts of Europe, the Pacific, and North Africa",
  },
  {
    id: '1c326c44-f2e5-4d2a-a144-5f0961349efc',
    release: 'November 5, 2007 ',
    year: 2007,
    rating: 8,
    cover: CoD5,
    fullName:  'Call of Duty 4: Modern Warfare',
    shortName: 'Call of Duty 4: MW',
    genres: ['FPS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 80,
    platforms:  ['Microsoft Windows', 'PlayStation 3', 'Xbox 360'],
    developers: ['Infinity Ward'],
    publishers: ['Activision'],
    description: "Call of Duty 4: Modern Warfare is a 2007 first-person shooter video game developed by Infinity Ward and published by Activision. It is the fourth main installment in the Call of Duty series. The game breaks away from the World War II setting of previous entries and is instead set in modern times",
  },
  {
    id: '5cddeec0-b4cd-4693-b9d1-bd7761ab55d8',
    release: 'November 4, 2016',
    year: 2016,
    rating: 6,
    cover: CoD6,
    fullName:  'Call of Duty: Modern Warfare Remastered',
    shortName: 'Call of Duty: MW Remastered',
    genres: ['FPS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 170,
    platforms:  ['Microsoft Windows', 'PlayStation 4', 'Xbox One'],
    developers: ['Raven Software'],
    publishers: ['Activision'],
    description: "Call of Duty®4: Modern Warfare®, is back, remastered in true high-definition, featuring enhanced textures, rendering, high-dynamic range lighting, and much more to bring a new generation experience to fans. Available on disc and digital download first on PS4. Standard Edition Includes: Modern Warfare® Remastered",
  },
  {
    id: '95725d77-0da1-4e66-b6c5-e17c7dd76152',
    release: 'November 10, 2009',
    year: 2009,
    rating: 5,
    cover: CoD7,
    fullName:  'Call of Duty: Modern Warfare 2',
    shortName: 'Call of Duty: MW 2',
    genres: ['FPS'],
    mode: ['Multiplayer', 'Cooperative', 'Single-player'],
    price: 120,
    platforms:  ['Microsoft Windows', 'PlayStation 3', 'Xbox 360'],
    developers: ['Infinity Ward'],
    publishers: ['Activision'],
    description: "MODERN WARFARE® II WILL FEATURE A MASSIVE AMOUNT OF CONTENT FROM DAY 1. Squad up and fight alongside Task Force 141 in a globe-trotting single-player campaign. Play lone-wolf or rally with your team in immersive multiplayer combat, complete with new locales and ways to play",
  },
  {
    id: 'ffdc546f-01b6-46b2-9159-0bae7667fd71',
    release: 'November 8, 2011',
    year: 2011,
    rating: 4,
    cover: CoD8,
    fullName:  'Call of Duty: Modern Warfare 3',
    shortName: 'Call of Duty: MW 3',
    genres: ['FPS'],
    mode: ['Multiplayer','Cooperative', 'Single-player'],
    price: 110,
    platforms:  ['Microsoft Windows', 'PlayStation 3', 'Xbox 360'],
    developers: ['Infinity Ward', 'Sledgehammer Games'],
    publishers: ['Activision'],
    description: "Modern Warfare 3 takes place after the events of Modern Warfare 2. The Russian Federation has declared war against the United States, and also takes it's offensive into Europe, including England, France, and Germany. Missions will also take place in other countries around the world",
  },
  {
    id: 'e7492ec1-e4bd-4810-bac1-07cc374411d7',
    release: 'October 25, 2019',
    year: 2019,
    rating: 8,
    cover: CoD9,
    fullName:  'Call of Duty: Modern Warfare',
    shortName: 'Call of Duty: MW',
    genres: ['FPS'],
    mode: ['Multiplayer'],
    price: 250,
    platforms:  ['Microsoft Windows', 'PlayStation 4', 'Xbox One'],
    developers: ['Infinity Ward'],
    publishers: ['Activision'],
    description: 'Call of Duty: Modern Warfare is a 2019 first-person shooter game developed by Infinity Ward and published by Activision. Serving as the sixteenth overall installment in the Call of Duty series, as well as a reboot of the Modern Warfare sub-series, it was released on October 25, 2019, for PlayStation 4, Windows, and Xbox One.',
  },
  {
    id: 'b2f9a7f9-4a0e-4ac6-b81e-16d2e9af54ac',
    release: 'October 28, 2022',
    year: 2022,
    rating: 9,
    cover: CoD10,
    fullName:  'Call of Duty: Modern Warfare II',
    shortName: 'Call of Duty: MW II',
    genres: ['FPS'],
    mode: ['Multiplayer', 'Single-player'],
    price: 270,
    platforms:  ['Microsoft Windows', 'PlayStation 4', 'PlayStation 5', 'Xbox One'],
    developers: ['Infinity Ward'],
    publishers: ['Activision'],
    description: 'Call of Duty: Modern Warfare II is an upcoming first-person shooter game developed by Infinity Ward and published by Activision. It is a direct sequel to the 2019 reboot, and will serve as the nineteenth installment in the overall Call of Duty series. It is scheduled to be released on October 28, 2022, for PlayStation 4, PlayStation 5, Windows, Xbox One, and Xbox Series X/S.',
  },


] as GameCard_Type[]